### ISSUE TITLE
mutual information calculation

### ISSUE THREAD

**Issue by mynameisvinn** [mynameisvinn/basilisk#9]
@q1park can we compare mutual information calculations? 

assuming the following observations of two binary random variables:

1. n(cloudy=true, rain=true) = 70
2. n(cloudy=true, rain=false) = 50
3. n(cloudy=false, rain=true) = 5
4. n(cloudy=false, rain=false) = 100

then the calculated mutual information is **0.185**. is this what you get?

**Comment by q1park** [comment]
yesiree bob! here is my MI table for all pairs.. I was going to write the unittest today after my morning errand and calculate by hand to check.. beat me to it!

0.1455 cloudy rain
0.1852 cloudy rain
0.0643 cloudy sprinkler
0.1693 cloudy sprinkler
0.0244 cloudy wet
0.0897 cloudy wet
0.1455 rain cloudy
0.1852 rain cloudy
0.0003 rain sprinkler
0.2115 rain sprinkler
0.1693 sprinkler cloudy
0.1472 sprinkler wet
0.0244 wet cloudy
0.0897 wet cloudy
0.1833 wet rain
0.3548 wet rain
0.1472 wet sprinkler
0.2533 wet sprinkler
0.1455 cloudy rain
0.0643 cloudy sprinkler
0.0244 cloudy wet
0.0244 wet cloudy
0.1833 wet rain
0.1472 wet sprinkler

**Comment by mynameisvinn** [comment]
for an example on running unittests, do `python test.py`.

**Comment by q1park** [comment]
thanks! sorry I got derailed by a bad influence yesterday.. tried my own unittest this morning with some issues that I mentioned in the pull request.. reiterating them here since i'm still a little unsure about the appropriate avenue for various comment types..

issues:
1) from what I've seen it seems like good practice to create separate test modules for different .py files so I've done that here, although I may be wrong?
2) having trouble getting unittest to find the testfile, despite the file name being a valid identifier.. does not work unless the directory path for the test is specified

python -m unittest discover basilisk/_tests/

**Comment by q1park** [comment]
kewl travis is badass
